pipeline{
    agent any
    stages{
        stage('run image')
        {
            steps{
                 echo "run container"
                 docker.image('helloworldlatest:0.0.1-SNAPSHOT').pull()

            }
        }

    }
}