pipeline{
    agent {
    docker{
    image 'ragu/helloworldapi:v4'
    }
    }
    stages{
        stage('run image')
        {
            steps{
                 echo "pull succcess"
            }
        }

    }
}