pipeline{
    agent any
    stages{
        stage('build')
        {
            steps{
                 echo "ragu build"
                 sh 'mvn clean package'
            }
        }
        stage('testing')
        {
            steps{
                 echo "ragu test"
            }
        }
    }
}